### ISSUE TITLE
App kann im Browser nicht ausgeführt werden

### ISSUE THREAD

**Issue by Jojo-me** [BogyMitutoyoCTL/BOGY-App-2022-10#32]
Datenspeicherung so im Browser nicht möglich.

[Evtl. shared_preferences nutzen](https://pub.dev/packages/shared_preferences?ref=morioh.com&utm_source=morioh.com)

**Comment by dieterblocher** [comment]
Issue fixed with try catch blocks, when working with local file-system. Browser do not support working with local file system.

**Comment by dieterblocher** [comment]
Issue fixed with try catch blocks, when working with local file-system. Browser do not support working with local file system.
